I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 383, in script
    $ inv.add_item(alc_list)
  File "game/script.rpy", line 383, in <module>
    $ inv.add_item(alc_list)
  File "game/items.rpy", line 9, in add_item
    item.recieve()
AttributeError: 'RevertableList' object has no attribute 'recieve'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 383, in script
    $ inv.add_item(alc_list)
  File "C:\Users\Vile\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Vile\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 383, in <module>
    $ inv.add_item(alc_list)
  File "game/items.rpy", line 9, in add_item
    item.recieve()
AttributeError: 'RevertableList' object has no attribute 'recieve'

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Derleth Manor 1.0
Fri Mar 22 13:11:58 2024
